sed -i -E 's/ModelState\.AddModelError\(nameof\(Kategori\.Ad\), "اسم الفئة إلزامي."\);/ModelState.AddModelError(nameof(Kategori.Ad), _localizer["Admin_Category_NameRequired"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/KategoriController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Kategori\.ParentKategoriId\), "لا يمكن أن تكون الفئة فرعًا لنفسها."\);/ModelState.AddModelError(nameof(Kategori.ParentKategoriId), _localizer["Admin_Category_SelfParentError"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/KategoriController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Kategori\.ParentKategoriId\), "الفئة الرئيسية المحددة غير موجودة."\);/ModelState.AddModelError(nameof(Kategori.ParentKategoriId), _localizer["Admin_Category_ParentNotFoundError"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/KategoriController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Kategori\.ParentKategoriId\), "لا يمكن نقل فئة تحت أحد فروعها."\);/ModelState.AddModelError(nameof(Kategori.ParentKategoriId), _localizer["Admin_Category_ChildParentError"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/KategoriController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Kupon\.Tip\), "يرجى اختيار نوع خصم صالح."\);/ModelState.AddModelError(nameof(Kupon.Tip), _localizer["Admin_Coupon_InvalidType"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/KuponController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Kupon\.Deger\), "قيمة الخصم يجب أن تكون أكبر من صفر."\);/ModelState.AddModelError(nameof(Kupon.Deger), _localizer["Admin_Coupon_ValueGreaterThanZero"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/KuponController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Kupon\.Deger\), "لا يمكن أن يتجاوز خصم النسبة 100%."\);/ModelState.AddModelError(nameof(Kupon.Deger), _localizer["Admin_Coupon_ValueMax100"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/KuponController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Kupon\.MinSepetTutari\), "الحد الأدنى لسلة التسوق لا يمكن أن يكون سالبًا."\);/ModelState.AddModelError(nameof(Kupon.MinSepetTutari), _localizer["Admin_Coupon_MinCartNotNegative"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/KuponController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Kupon\.KullanimLimiti\), "لا يمكن أن يكون حد الاستخدام سالبًا. للاستخدام غير المحدود أدخل 0."\);/ModelState.AddModelError(nameof(Kupon.KullanimLimiti), _localizer["Admin_Coupon_LimitNotNegative"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/KuponController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Kupon\.SonKullanmaTarihi\), "يرجى اختيار تاريخ صلاحية صالح."\);/ModelState.AddModelError(nameof(Kupon.SonKullanmaTarihi), _localizer["Admin_Coupon_InvalidDate"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/KuponController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Kupon\.Kod\), "كود الخصم هذا مستخدم بالفعل."\);/ModelState.AddModelError(nameof(Kupon.Kod), _localizer["Admin_Coupon_CodeInUse"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/KuponController.cs
sed -i -E 's/ModelState\.AddModelError\("Video", "يتطلب السلايد من نوع فيديو رفع فيديو أو إدخال رابط الفيديو."\);/ModelState.AddModelError("Video", _localizer["Admin_Slide_VideoRequired"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/SlaytController.cs
sed -i -E 's/ModelState\.AddModelError\("Resim", "يتطلب السلايد من نوع صورة رفع صورة أو إدخال رابط الصورة."\);/ModelState.AddModelError("Resim", _localizer["Admin_Slide_ImageRequired"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/SlaytController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Urun\.Baslik\), "اسم المنتج إلزامي."\);/ModelState.AddModelError(nameof(Urun.Baslik), _localizer["Admin_Product_NameRequired"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Urun\.KategoriId\), "يرجى اختيار فئة صالحة."\);/ModelState.AddModelError(nameof(Urun.KategoriId), _localizer["Admin_Product_CategoryRequired"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Urun\.Fiyat\), "سعر البيع يجب أن يكون أكبر من صفر."\);/ModelState.AddModelError(nameof(Urun.Fiyat), _localizer["Admin_Product_PriceGreaterThanZero"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Urun\.IndirimliFiyat\), "السعر المخفَّض يجب أن يكون أقل من السعر الأصلي."\);/ModelState.AddModelError(nameof(Urun.IndirimliFiyat), _localizer["Admin_Product_DiscountPriceLowerThanOriginal"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Urun\.MinSiparisAdedi\), "الحد الأدنى للطلب يجب أن يكون 1 على الأقل."\);/ModelState.AddModelError(nameof(Urun.MinSiparisAdedi), _localizer["Admin_Product_MinOrderAtLeastOne"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Urun\.MaxSiparisAdedi\), "الحد الأقصى للطلب لا يمكن أن يكون أقل من الحد الأدنى."\);/ModelState.AddModelError(nameof(Urun.MaxSiparisAdedi), _localizer["Admin_Product_MaxOrderLowerThanMin"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
sed -i -E 's/ModelState\.AddModelError\(nameof\(Urun\.AnaGorselUrl\), "يرجى رفع صورة رئيسية أو إدخال رابط صورة."\);/ModelState.AddModelError(nameof(Urun.AnaGorselUrl), _localizer["Admin_Product_MainImageRequired"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
sed -i -E 's/ModelState\.AddModelError\(\$"{prefix}\.MinAdet", "يجب أن يكون الحد الأدنى للكمية أكبر من صفر."\);/ModelState.AddModelError($"{prefix}.MinAdet", _localizer["Admin_Product_VariantMinQtyZero"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
sed -i -E 's/ModelState\.AddModelError\(\$"{prefix}\.BirimFiyat", "يجب أن يكون سعر الوحدة أكبر من صفر."\);/ModelState.AddModelError($"{prefix}.BirimFiyat", _localizer["Admin_Product_VariantUnitPriceZero"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
sed -i -E 's/ModelState\.AddModelError\(\$"{prefix}\.Id", "درجة السعر المحددة لا تنتمي إلى هذا المنتج."\);/ModelState.AddModelError($"{prefix}.Id", _localizer["Admin_Product_VariantPriceTierInvalid"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
sed -i -E 's/ModelState\.AddModelError\(\$"{prefix}\.UrunSecenekId", "المتغير المحدد لا ينتمي إلى هذا المنتج أو تم حذفه."\);/ModelState.AddModelError($"{prefix}.UrunSecenekId", _localizer["Admin_Product_VariantInvalid"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
sed -i -E 's/ModelState\.AddModelError\(\$"{prefix}\.MinAdet", "لا يمكن تكرار نفس الحد الأدنى للكمية ضمن المنتج أو المتغير نفسه."\);/ModelState.AddModelError($"{prefix}.MinAdet", _localizer["Admin_Product_VariantDuplicateMinQty"].Value);/g' FilistinProje.Web/Areas/Admin/Controllers/UrunController.cs
