import xml.etree.ElementTree as ET
import os

# Read all keys
with open("localizer_keys.txt", "r", encoding="utf-8") as f:
    keys = [line.strip() for line in f if line.strip()]

# Auto-generate English and Arabic
en_values = {}
ar_values = {}

key_to_en = {
    "12Installments": "12 Installments",
    "256BitSSL": "256 Bit SSL",
    "256BitSsl": "256 Bit SSL",
    "256BitSslDescription": "Secure shopping with 256 bit SSL certificate",
    "256BitSslEncryption": "256 Bit SSL Encryption",
    "5Piece": "5-Piece Set",
    "AboutUs": "About Us",
    "AccessDenied": "Access Denied",
    "AccessDeniedDescription": "You do not have permission to access this page",
    "AccountInfo": "Account Info",
    "AccountVerified": "Account Verified",
    "ActiveMember": "Active Member",
    "AddAddress": "Add Address",
    "AddAddressToSpeedUp": "Add address for faster checkout",
    "AddNewAddress": "Add New Address",
    "AddToCart": "Add to Cart",
    "AddToFavorites": "Add to Favorites",
    "Added": "Added",
    "AddedToCartSuccess": "Successfully added to cart",
    "Address": "Address",
    "AddressLoaded": "Address loaded",
    "AddressTitle": "Address Title",
    "AddressTitlePlaceholder": "Home, Work, etc.",
    "Addresses": "Addresses",
    "All": "All",
    "AllCategoryPrefix": "All",
    "AllCollections": "All Collections",
    "AllCreditCards": "All Credit Cards",
    "AllOverTurkey": "Across Palestine",
    "AllProducts": "All Products",
    "AllRightsReserved": "All rights reserved",
    "AlreadyHaveAccount": "Already have an account?",
    "AmountLabel": "Amount",
    "AnErrorOccurred": "An error occurred",
    "And": "and",
    "Apply": "Apply",
    "BackToList": "Back to List",
    "BackToShopping": "Back to Shopping",
    "BeFirstToReview": "Be the first to review",
    "BestSellers": "Best Sellers",
    "Bestseller": "Best Seller",
    "Bestsellers": "Best Sellers",
    "BrowseProducts": "Browse Products",
    "BrowseProductsToOrder": "Browse products to place an order",
    "BusinessDaysJS": "Business Days",
    "CampaignSelections": "Campaign Selections",
    "Cancel": "Cancel",
    "CancelRequest": "Cancel Request",
    "CancelledOrder": "Order Cancelled",
    "CancelledOrderMessage": "Your order has been cancelled",
    "CarefulDelivery": "Careful Delivery",
    "CarefulPackaging": "Careful Packaging",
    "CarefullyPackaged": "Carefully Packaged",
    "CarefullyPackagedDesc": "Your products are carefully packaged and shipped",
    "Cart": "Cart",
    "CartEmpty": "Your Cart is Empty",
    "Categories": "Categories",
    "Category": "Category",
    "CategoryDetail": "Category Detail",
    "CheckFormInfo": "Check form information",
    "City": "District",
    "ClearCart": "Clear Cart",
    "ClearCartConfirm": "All items in your cart will be removed",
    "CloseImage": "Close Image",
    "CloseMenu": "Close Menu",
    "Collection": "Collection",
    "Collections": "Collections",
    "ConfirmDeleteAccount": "Are you sure you want to delete your account?",
    "ConfirmDeleteAddress": "Are you sure you want to delete this address?",
    "ConfirmRemoveFavorite": "Are you sure you want to remove from favorites?",
    "ConfirmationEmail": "Confirmation Email",
    "Confirmed": "Confirmed",
    "ConnectionError": "Connection Error",
    "ConnectionErrorOccurred": "A connection error occurred",
    "ConnectionErrorShort": "Connection error",
    "Contact": "Contact",
    "ContactUs": "Contact Us",
    "ContinueShopping": "Continue Shopping",
    "Copied": "Copied",
    "Copy": "Copy",
    "CopyLink": "Copy Link",
    "Corporate": "Corporate",
    "CreateMembership": "Create Membership",
    "CreateNewAccount": "Create New Account",
    "CreateOrder": "Create Order",
    "CreateReturnRequest": "Create Return Request",
    "CreateReturnRequestTitle": "Return Request Form",
    "CreditCardPayment": "Credit Card Payment",
    "CustomerSatisfaction": "Customer Satisfaction",
    "CustomerSatisfactionDesc": "100% customer satisfaction focused service",
    "DateLabel": "Date",
    "Deal": "Deal",
    "DealProducts": "Deal Products",
    "DeleteAccount": "Delete Account",
    "DeleteAccountMessage": "Your account will be permanently deleted",
    "DeleteAccountWarning": "This action cannot be undone",
    "DeleteAddress": "Delete Address",
    "Delivery": "Delivery",
    "DeliveryAddress": "Delivery Address",
    "DeliveryDescription": "Your order is carefully prepared and delivered",
    "DeliveryInfo": "Delivery Info",
    "DescriptionOptional": "Description (Optional)",
    "DesignPrepared": "Design Prepared",
    "DesignPreparedDesc": "Your design is prepared with care",
    "Detail": "Detail",
    "Discount": "Discount",
    "DiscountCode": "Discount Code",
    "DistanceSalesContract": "Distance Sales Contract",
    "District": "Neighborhood",
    "DistrictPlaceholder": "Neighborhood name",
    "DocumentsAndRecords": "Documents and Records",
    "DownloadInvoice": "Download Invoice",
    "EasyReturnDays": "14 Days Return",
    "EasyReturns": "Easy Returns",
    "EasyReturnsDescription": "No-questions-asked return within 14 days",
    "Email": "Email",
    "EmailAddress": "Email Address",
    "EmailConfirmation": "Email Confirmation",
    "EmailConfirmationErrorDescription": "Confirmation link is invalid or expired",
    "EmailConfirmationRequired": "Email confirmation required",
    "EmailConfirmationSuccessDescription": "Your email address has been verified",
    "EmailPlaceholder": "example@email.com",
    "EnterPasswordAgain": "Enter Your Password Again",
    "Error": "Error",
    "ErrorDetails": "Error Details",
    "ErrorOccurred": "An error occurred",
    "ExampleEmail": "example@email.com",
    "ExploreCartEmpty": "Explore Cart",
    "ExploreCategory": "Explore Category",
    "ExploreCollection": "Explore Collection",
    "ExploreCollectionProducts": "Explore collection products",
    "ExploreFavoriteCollection": "Explore Favorite Collection",
    "ExploreFeaturedDesigns": "Explore Featured Designs",
    "Facebook": "Facebook",
    "FastDelivery": "Fast Delivery",
    "FastDeliveryDesc": "Your orders arrive quickly",
    "FastProduction": "Fast Production",
    "FavoriteCollection": "My Favorite Collection",
    "FavoriteDescription": "Add products you like to your favorites",
    "FavoriteRemoved": "Removed from favorites",
    "Favorites": "My Favorites",
    "FeaturedProducts": "Featured Products",
    "FeaturedProductsSubtitle": "Most popular designs",
    "FeaturedWorks": "Featured Works",
    "Features": "Features",
    "FillRequiredFields": "Please fill in required fields",
    "ForgotPassword": "Forgot Password",
    "ForgotPasswordDescription": "Enter your email and we will send you a reset link",
    "FrameLabel": "Frame",
    "FrameSelectionRequired": "Frame selection is required",
    "Free": "Free",
    "FreeShipping": "Free Shipping",
    "FreeShippingLimit": "Free shipping on orders over",
    "FromProductionToDelivery": "From Production to Delivery",
    "FullAddress": "Full Address",
    "FullAddressPlaceholder": "Street, avenue, building no, apartment no...",
    "FullName": "Full Name",
    "FullNamePlaceholder": "Your name and surname",
    "GetSupport": "Get Support",
    "GrandTotal": "Grand Total",
    "HaveQuestions": "Have Questions?",
    "HomeMetaDescription": "Canvas prints and posters at affordable prices",
    "HomeMetaKeywords": "canvas, painting, poster, print, decoration",
    "HomePage": "Home Page",
    "HomeSeoTitle": "Canvas Print & Poster - 7ANRPS48",
    "HomepageSlider": "Homepage Slider",
    "IBANOptional": "IBAN (Optional)",
    "IBANPlaceholder": "PS00 0000 0000 0000 0000 0000",
    "Instagram": "Instagram",
    "Invoice": "Invoice",
    "InvoiceNotCreated": "Invoice not yet created",
    "Login": "Login",
    "LoginRegister": "Login / Register",
    "LoginToYourAccount": "Login to Your Account",
    "Logout": "Logout",
    "LongLastingTouch": "Long Lasting Use",
    "MadeToOrder": "Made to Order",
    "ManageDeliveryAddresses": "Manage Delivery Addresses",
    "ManufacturerGuarantee": "Manufacturer Guarantee",
    "MaterialAndPrintQuality": "Material and Print Quality",
    "MaterialLabel": "Material",
    "MaterialQualityDesc1": "First-class material quality",
    "MaterialQualityDesc2": "Non-fading print technology",
    "Max": "Max",
    "Max500Chars": "Maximum 500 characters",
    "MediaAndGalleries": "Media and Galleries",
    "Min": "Min",
    "MinSixChars": "At least 6 characters",
    "MostPreferred": "Most Preferred",
    "MyAccount": "My Account",
    "MyAddresses": "My Addresses",
    "MyCart": "My Cart",
    "MyFavorites": "My Favorites",
    "MyOrders": "My Orders",
    "New": "New",
    "NewAddress": "New Address",
    "NewPassword": "New Password",
    "Newest": "Newest",
    "NewsletterDescription": "Stay informed about campaigns and deals",
    "NextSlide": "Next Slide",
    "NoAccount": "Don't have an account?",
    "NoAddressesSaved": "No saved addresses",
    "NoDescription": "No description",
    "NoFavorites": "No favorite products",
    "NoOrdersYet": "No orders yet",
    "NoResultsFound": "No results found",
    "NoReviewsYet": "No reviews yet",
    "NotSpecified": "Not Specified",
    "NoteLabel": "Note",
    "NotePlaceholder": "Note about your order",
    "NoteSpecialRequest": "Special request note",
    "NotificationOn": "Notification On",
    "NotifyPriceDrop": "Notify me when price drops",
    "NotifyPriceDropTitle": "Price Drop Notification",
    "OpenInInstagram": "Open in Instagram",
    "OpenMenu": "Open Menu",
    "OperationFailed": "Operation failed",
    "OrderCompleteDescription": "Your order has been completed successfully",
    "OrderDetail": "Order Detail",
    "OrderInfo": "Order Info",
    "OrderNo": "Order No",
    "OrderNoLabel": "Order Number",
    "OrderNumber": "Order Number",
    "OrderPendingInfo": "Your order is being processed",
    "OrderProcessingDescription": "Your order is being prepared",
    "OrderReceived": "Order Received",
    "OrderReceivedTitle": "Your Order is Received",
    "OrderRecordAdded": "Order record created",
    "OrderRequest": "Order Request",
    "OrderRequestInfo": "Your order request has been received",
    "OrderSummary": "Order Summary",
    "OrderTracking": "Order Tracking",
    "Orders": "Orders",
    "OutOfStock": "Out of Stock",
    "Overview": "Overview",
    "Packaging": "Packaging",
    "PackagingLabel": "Packaging",
    "Password": "Password",
    "PasswordPlaceholder": "Your password",
    "PasswordRepeat": "Repeat Password",
    "PaymentAndDelivery": "Payment and Delivery",
    "PaymentApprovalPending": "Payment Approval Pending",
    "PaymentErrorDescription": "An error occurred during payment",
    "PaymentFailed": "Payment Failed",
    "PaymentFailedTitle": "Payment Failed",
    "PaymentInfo": "Payment Info",
    "PaymentMethod": "Payment Method",
    "PaymentMethods": "Payment Methods",
    "PaymentStatus": "Payment Status",
    "PaymentSuccessful": "Payment Successful",
    "Phone": "Phone",
    "PhonePlaceholder": "+970 5XX XXX XXX",
    "Pinterest": "Pinterest",
    "PleaseLogin": "Please login",
    "PleaseWait": "Please wait",
    "PreOrder": "Pre-Order",
    "PreOrderOpen": "Open for Pre-Order",
    "Preparing": "Preparing",
    "PreparingDescription": "Your order is being prepared",
    "PreviousSlide": "Previous Slide",
    "PriceDropNotificationOn": "Price drop notification on",
    "PriceHighToLow": "Price High to Low",
    "PriceLowToHigh": "Price Low to High",
    "PriceRange": "Price Range",
    "PrivacyPolicy": "Privacy Policy",
    "ProceedToCheckout": "Proceed to Checkout",
    "ProcessFailed": "Process failed",
    "Processing": "Processing",
    "Product": "Product",
    "ProductAddFailed": "Failed to add product",
    "ProductAdded": "Product added",
    "ProductAddedToCart": "Product added to cart",
    "ProductAddedToFavorites": "Product added to favorites",
    "ProductDescription": "Product Description",
    "ProductImage": "Product Image",
    "ProductLink": "Product Link",
    "ProductNotAvailable": "Product not available",
    "ProductNotFound": "Product not found",
    "ProductPrepared": "Product Prepared",
    "ProductPreparedDesc": "Your product is made to order",
    "ProductRemovedFromFavorites": "Product removed from favorites",
    "Production": "Production",
    "ProductionInDaysJS": "Deal Products",
    "ProductionQualityAlt": "Production quality",
    "ProductionStoryDesc": "Every product is made with care",
    "ProtectivePackaging": "Protective Packaging",
    "PurchasedProducts": "Purchased Products",
    "QualityPrint": "Quality Print",
    "QualityPrintDesc": "Vibrant colors and sharp details",
    "Quantity": "Quantity",
    "RateProduct": "Rate Product",
    "RateProductShort": "Rate",
    "ReasonChangedMind": "Changed My Mind",
    "ReasonDamagedProduct": "Product Damaged",
    "ReasonNotAsExpected": "Not as Expected",
    "ReasonWrongProduct": "Wrong Product Received",
    "RecipientPlaceholder": "Recipient name",
    "Register": "Register",
    "RegisteredEmail": "Registered Email",
    "RegisteredEmailUsed": "This email is already registered",
    "RemoveFromFavorites": "Remove from Favorites",
    "RemoveProduct": "Remove Product",
    "ResetPassword": "Reset Password",
    "ResetPasswordDescription": "Set your new password",
    "ResultsFound": "results found",
    "ReturnDescriptionPlaceholder": "Explain the reason for return",
    "ReturnExchange": "Return and Exchange",
    "ReturnGuarantee": "Return Guarantee",
    "ReturnHome": "Return Home",
    "ReturnProcess": "Return Process",
    "ReturnProcessActive": "Return process started",
    "ReturnReason": "Return Reason",
    "ReturnRequest": "Return Request",
    "ReturnToCartAndRetry": "Return to Cart and Retry",
    "ReturnToHome": "Return to Home",
    "ReturnToLogin": "Return to Login",
    "Review": "Review",
    "Reviews": "Reviews",
    "Rotate": "Rotate",
    "Sale": "Sale",
    "Save": "Save",
    "SaveAddress": "Save Address",
    "SaveAddressToAccount": "Address will be saved to your account",
    "SavedAddresses": "Saved Addresses",
    "SavedNote": "Note saved",
    "Search": "Search",
    "SearchProducts": "Search Products",
    "SearchUnavailable": "Search unavailable",
    "SecurePayment": "Secure Payment",
    "SecurePaymentDesc": "Secure payment with 256 bit SSL",
    "SecureShopping": "Secure Shopping",
    "SelectCity": "Select City",
    "SelectFrame": "Select Frame",
    "SelectFrameModel": "Select Frame Model",
    "SelectOption": "Select Option",
    "SelectShippingCompany": "Select Shipping Company",
    "SelectSize": "Select Size",
    "SendLink": "Send Link",
    "Sending": "Sending",
    "Sent": "Sent",
    "SentViaEmail": "Sent via email",
    "Share": "Share",
    "ShareOnFacebook": "Share on Facebook",
    "ShareOnWhatsApp": "Share on WhatsApp",
    "Shipped": "Shipped",
    "ShippedDesc": "Your product has been shipped",
    "ShippedDescription": "Your order has been shipped",
    "Shipping": "Shipping",
    "ShippingFee": "Shipping Fee",
    "ShippingLabel": "Shipping",
    "SimilarProducts": "Similar Products",
    "SizeOptions": "Size Options",
    "SlideN": "Slide",
    "SpecialSelections": "Special Selections",
    "SslSecurePayment": "SSL Secure Payment",
    "StartShopping": "Start Shopping",
    "Status": "Status",
    "StatusCancelled": "Cancelled",
    "StatusDelivered": "Delivered",
    "StatusOrderReceived": "Order Received",
    "StatusPackaging": "Packaging",
    "StatusPreparing": "Preparing",
    "StatusReturnApproved": "Return Approved",
    "StatusReturnCompleted": "Return Completed",
    "StatusReturnRequest": "Return Request",
    "StatusShipped": "Shipped",
    "StepApproved": "Approved",
    "StepDelivered": "Delivered",
    "StepInTransit": "In Transit",
    "StepOrderReceived": "Order Received",
    "StepPackaging": "Packaging",
    "StepProcessClosed": "Process Closed",
    "StepProductionPreparing": "Production Preparation",
    "StepRequestReceived": "Request Received",
    "StepReturnCompleted": "Return Completed",
    "Subcategories": "Subcategories",
    "SubmitRequest": "Submit Request",
    "SubmitReview": "Submit Review",
    "Subscribe": "Subscribe",
    "SubscribeToNewsletter": "Subscribe to newsletter",
    "Subtotal": "Subtotal",
    "SuccessfullySubscribed": "Successfully subscribed",
    "SupportContactInfo": "Support contact info",
    "TechnicalSpecs": "Technical Specifications",
    "TermsAccepted": "I accept the terms",
    "TermsOfUse": "Terms of Use",
    "TikTok": "TikTok",
    "Total": "Total",
    "TotalOrders": "Total Orders",
    "TotalSpent": "Total Spent",
    "TrackOrder": "Track Order",
    "TrackingNumber": "Tracking Number",
    "TransactionTime": "Transaction Time",
    "TryDifferentCategoryOrSearch": "Try a different category or search",
    "TurkeyWideShipping": "Delivery Across Palestine",
    "UnauthorizedAccess": "Unauthorized Access",
    "UndamagedDelivery": "Undamaged Delivery",
    "UndamagedDeliveryDescription": "Undamaged delivery with careful packaging",
    "UnitPrice": "Unit Price",
    "UpdatePassword": "Update Password",
    "UserAgreement": "User Agreement",
    "VerificationSuccessDescription": "Your account has been verified",
    "VerificationSuccessful": "Verification Successful",
    "VerifyDeliveryInfo": "Verify delivery information",
    "VibrantColors": "Vibrant Colors",
    "VideoTutorial": "Video Tutorial",
    "ViewAll": "View All",
    "ViewAll5Piece": "View All 5-Piece Sets",
    "ViewAllProducts": "View All Products",
    "ViewAllResults": "View All Results",
    "ViewDeals": "View Deals",
    "WelcomeToAccount": "Welcome to Your Account",
    "WhatsApp": "WhatsApp",
    "WhatsAppContact": "WhatsApp Contact",
    "WhatsAppSupport": "WhatsApp Support",
    "WriteFirstReview": "Write First Review",
    "WriteReview": "Write Review",
    "X": "X",
    "YouTube": "YouTube",
    "YourComment": "Your Comment",
    "YourFullName": "Your Full Name",
    "YourOrderPreparedWithCare": "Your order is being prepared with care",
    "ZoomIn": "Zoom In",
    "ZoomOut": "Zoom Out",
}

ar_values = {
    "12Installments": "12 قسط",
    "256BitSSL": "256 بت SSL",
    "256BitSsl": "256 بت SSL",
    "256BitSslDescription": "تسوق آمن مع شهادة SSL 256 بت",
    "256BitSslEncryption": "تشفير SSL 256 بت",
    "5Piece": "مجموعة 5 قطع",
    "AboutUs": "من نحن",
    "AccessDenied": "تم رفض الوصول",
    "AccessDeniedDescription": "ليس لديك صلاحية الوصول إلى هذه الصفحة",
    "AccountInfo": "معلومات الحساب",
    "AccountVerified": "تم التحقق من الحساب",
    "ActiveMember": "عضو نشط",
    "AddAddress": "إضافة عنوان",
    "AddAddressToSpeedUp": "أضف عنوانًا للشراء السريع",
    "AddNewAddress": "إضافة عنوان جديد",
    "AddToCart": "أضف إلى السلة",
    "AddToFavorites": "أضف إلى المفضلة",
    "Added": "تمت الإضافة",
    "AddedToCartSuccess": "تمت الإضافة إلى السلة بنجاح",
    "Address": "العنوان",
    "AddressLoaded": "تم تحميل العنوان",
    "AddressTitle": "عنوان العنوان",
    "AddressTitlePlaceholder": "منزلي، عملي، إلخ.",
    "Addresses": "عناويني",
    "All": "الكل",
    "AllCategoryPrefix": "جميع",
    "AllCollections": "جميع المجموعات",
    "AllCreditCards": "جميع بطاقات الائتمان",
    "AllOverTurkey": "في جميع مناطق فلسطين",
    "AllProducts": "جميع المنتجات",
    "AllRightsReserved": "جميع الحقوق محفوظة",
    "AlreadyHaveAccount": "هل لديك حساب بالفعل؟",
    "AmountLabel": "المبلغ",
    "AnErrorOccurred": "حدث خطأ",
    "And": "و",
    "Apply": "تطبيق",
    "BackToList": "العودة إلى القائمة",
    "BackToShopping": "العودة للتسوق",
    "BeFirstToReview": "كن أول من يقيّم",
    "BestSellers": "الأكثر مبيعاً",
    "Bestseller": "الأكثر مبيعاً",
    "Bestsellers": "الأكثر مبيعاً",
    "BrowseProducts": "تصفح المنتجات",
    "BrowseProductsToOrder": "تصفح المنتجات لتقديم طلب",
    "BusinessDaysJS": "أيام عمل",
    "CampaignSelections": "اختيارات الحملات",
    "Cancel": "إلغاء",
    "CancelRequest": "إلغاء الطلب",
    "CancelledOrder": "تم إلغاء الطلب",
    "CancelledOrderMessage": "تم إلغاء طلبك",
    "CarefulDelivery": "توصيل دقيق",
    "CarefulPackaging": "تغليف دقيق",
    "CarefullyPackaged": "معبأ بعناية",
    "CarefullyPackagedDesc": "يتم تعبئة منتجاتك بعناية وشحنها",
    "Cart": "السلة",
    "CartEmpty": "سلتك فارغة",
    "Categories": "التصنيفات",
    "Category": "التصنيف",
    "CategoryDetail": "تفاصيل التصنيف",
    "CheckFormInfo": "تحقق من معلومات النموذج",
    "City": "المنطقة",
    "ClearCart": "إفراغ السلة",
    "ClearCartConfirm": "سيتم إزالة جميع العناصر من سلتك",
    "CloseImage": "إغلاق الصورة",
    "CloseMenu": "إغلاق القائمة",
    "Collection": "مجموعة",
    "Collections": "المجموعات",
    "ConfirmDeleteAccount": "هل أنت متأكد من حذف حسابك؟",
    "ConfirmDeleteAddress": "هل أنت متأكد من حذف هذا العنوان؟",
    "ConfirmRemoveFavorite": "هل أنت متأكد من الإزالة من المفضلة؟",
    "ConfirmationEmail": "بريد التأكيد",
    "Confirmed": "تم التأكيد",
    "ConnectionError": "خطأ في الاتصال",
    "ConnectionErrorOccurred": "حدث خطأ في الاتصال",
    "ConnectionErrorShort": "خطأ في الاتصال",
    "Contact": "اتصل بنا",
    "ContactUs": "اتصل بنا",
    "ContinueShopping": "مواصلة التسوق",
    "Copied": "تم النسخ",
    "Copy": "نسخ",
    "CopyLink": "نسخ الرابط",
    "Corporate": "مؤسسي",
    "CreateMembership": "إنشاء عضوية",
    "CreateNewAccount": "إنشاء حساب جديد",
    "CreateOrder": "إنشاء طلب",
    "CreateReturnRequest": "إنشاء طلب إرجاع",
    "CreateReturnRequestTitle": "نموذج طلب الإرجاع",
    "CreditCardPayment": "الدفع ببطاقة الائتمان",
    "CustomerSatisfaction": "رضا العملاء",
    "CustomerSatisfactionDesc": "خدمة تركز على رضا العملاء 100%",
    "DateLabel": "التاريخ",
    "Deal": "عرض",
    "DealProducts": "منتجات العروض",
    "DeleteAccount": "حذف الحساب",
    "DeleteAccountMessage": "سيتم حذف حسابك بشكل دائم",
    "DeleteAccountWarning": "لا يمكن التراجع عن هذا الإجراء",
    "DeleteAddress": "حذف العنوان",
    "Delivery": "التوصيل",
    "DeliveryAddress": "عنوان التوصيل",
    "DeliveryDescription": "يتم تحضير طلبك بعناية وتوصيله",
    "DeliveryInfo": "معلومات التوصيل",
    "DescriptionOptional": "الوصف (اختياري)",
    "DesignPrepared": "تم تحضير التصميم",
    "DesignPreparedDesc": "يتم تحضير تصميمك بعناية",
    "Detail": "التفاصيل",
    "Discount": "خصم",
    "DiscountCode": "كود الخصم",
    "DistanceSalesContract": "عقد البيع عن بعد",
    "District": "الحي",
    "DistrictPlaceholder": "اسم الحي",
    "DocumentsAndRecords": "المستندات والسجلات",
    "DownloadInvoice": "تحميل الفاتورة",
    "EasyReturnDays": "إرجاع 14 يوم",
    "EasyReturns": "إرجاع سهل",
    "EasyReturnsDescription": "إرجاع بدون أسئلة خلال 14 يوم",
    "Email": "البريد الإلكتروني",
    "EmailAddress": "عنوان البريد الإلكتروني",
    "EmailConfirmation": "تأكيد البريد الإلكتروني",
    "EmailConfirmationErrorDescription": "رابط التأكيد غير صالح أو منتهي الصلاحية",
    "EmailConfirmationRequired": "تأكيد البريد الإلكتروني مطلوب",
    "EmailConfirmationSuccessDescription": "تم التحقق من بريدك الإلكتروني بنجاح",
    "EmailPlaceholder": "example@email.com",
    "EnterPasswordAgain": "أدخل كلمة المرور مرة أخرى",
    "Error": "خطأ",
    "ErrorDetails": "تفاصيل الخطأ",
    "ErrorOccurred": "حدث خطأ",
    "ExampleEmail": "example@email.com",
    "ExploreCartEmpty": "استكشاف السلة",
    "ExploreCategory": "استكشاف التصنيف",
    "ExploreCollection": "استكشاف المجموعة",
    "ExploreCollectionProducts": "استكشاف منتجات المجموعة",
    "ExploreFavoriteCollection": "استكشاف المجموعة المفضلة",
    "ExploreFeaturedDesigns": "استكشاف التصاميم المميزة",
    "Facebook": "فيسبوك",
    "FastDelivery": "توصيل سريع",
    "FastDeliveryDesc": "تصل طلباتك بسرعة",
    "FastProduction": "إنتاج سريع",
    "FavoriteCollection": "مجموعتي المفضلة",
    "FavoriteDescription": "أضف المنتجات التي تعجبك إلى المفضلة",
    "FavoriteRemoved": "تمت الإزالة من المفضلة",
    "Favorites": "المفضلة",
    "FeaturedProducts": "منتجات مميزة",
    "FeaturedProductsSubtitle": "أكثر التصاميم شعبية",
    "FeaturedWorks": "أعمال مميزة",
    "Features": "الميزات",
    "FillRequiredFields": "يرجى ملء الحقول الإلزامية",
    "ForgotPassword": "نسيت كلمة المرور",
    "ForgotPasswordDescription": "أدخل بريدك الإلكتروني وسنرسل رابط إعادة تعيين",
    "FrameLabel": "الإطار",
    "FrameSelectionRequired": "اختيار الإطار إلزامي",
    "Free": "مجاني",
    "FreeShipping": "شحن مجاني",
    "FreeShippingLimit": "شحن مجاني للطلبات فوق",
    "FromProductionToDelivery": "من الإنتاج إلى التوصيل",
    "FullAddress": "العنوان الكامل",
    "FullAddressPlaceholder": "الشارع، الجادة، رقم المبنى، رقم الشقة...",
    "FullName": "الاسم الكامل",
    "FullNamePlaceholder": "اسمك ولقبك",
    "GetSupport": "الحصول على الدعم",
    "GrandTotal": "المجموع الكلي",
    "HaveQuestions": "هل لديك أسئلة؟",
    "HomeMetaDescription": "مطبوعات كانفاس وملصقات بأسعار معقولة",
    "HomeMetaKeywords": "كانفاس، لوحة، ملصق، طباعة، ديكور",
    "HomePage": "الصفحة الرئيسية",
    "HomeSeoTitle": "مطبوعات كانفاس وملصقات - 7ANRPS48",
    "HomepageSlider": "شريط الصفحة الرئيسية",
    "IBANOptional": "IBAN (اختياري)",
    "IBANPlaceholder": "PS00 0000 0000 0000 0000 0000",
    "Instagram": "إنستغرام",
    "Invoice": "الفاتورة",
    "InvoiceNotCreated": "لم يتم إنشاء الفاتورة بعد",
    "Login": "تسجيل الدخول",
    "LoginRegister": "تسجيل الدخول / التسجيل",
    "LoginToYourAccount": "تسجيل الدخول إلى حسابك",
    "Logout": "تسجيل الخروج",
    "LongLastingTouch": "استخدام طويل الأمد",
    "MadeToOrder": "مصنوع حسب الطلب",
    "ManageDeliveryAddresses": "إدارة عناوين التوصيل",
    "ManufacturerGuarantee": "ضمان الشركة المصنعة",
    "MaterialAndPrintQuality": "جودة المواد والطباعة",
    "MaterialLabel": "المادة",
    "MaterialQualityDesc1": "جودة مواد من الدرجة الأولى",
    "MaterialQualityDesc2": "تقنية طباعة غير قابلة للبهتان",
    "Max": "الحد الأقصى",
    "Max500Chars": "500 حرف كحد أقصى",
    "MediaAndGalleries": "الوسائط والمعارض",
    "Min": "الحد الأدنى",
    "MinSixChars": "6 أحرف على الأقل",
    "MostPreferred": "الأكثر تفضيلاً",
    "MyAccount": "حسابي",
    "MyAddresses": "عناويني",
    "MyCart": "سلتي",
    "MyFavorites": "مفضلتي",
    "MyOrders": "طلباتي",
    "New": "جديد",
    "NewAddress": "عنوان جديد",
    "NewPassword": "كلمة مرور جديدة",
    "Newest": "الأحدث",
    "NewsletterDescription": "ابق على اطلاع بالحملات والعروض",
    "NextSlide": "الشريحة التالية",
    "NoAccount": "ليس لديك حساب؟",
    "NoAddressesSaved": "لا توجد عناوين محفوظة",
    "NoDescription": "لا يوجد وصف",
    "NoFavorites": "لا توجد منتجات مفضلة",
    "NoOrdersYet": "لا توجد طلبات بعد",
    "NoResultsFound": "لم يتم العثور على نتائج",
    "NoReviewsYet": "لا توجد تقييمات بعد",
    "NotSpecified": "غير محدد",
    "NoteLabel": "ملاحظة",
    "NotePlaceholder": "ملاحظة حول طلبك",
    "NoteSpecialRequest": "ملاحظة طلب خاص",
    "NotificationOn": "الإشعارات مفعلة",
    "NotifyPriceDrop": "أبلغني عند انخفاض السعر",
    "NotifyPriceDropTitle": "إشعار انخفاض السعر",
    "OpenInInstagram": "فتح في إنستغرام",
    "OpenMenu": "فتح القائمة",
    "OperationFailed": "فشلت العملية",
    "OrderCompleteDescription": "تم إتمام طلبك بنجاح",
    "OrderDetail": "تفاصيل الطلب",
    "OrderInfo": "معلومات الطلب",
    "OrderNo": "رقم الطلب",
    "OrderNoLabel": "رقم الطلب",
    "OrderNumber": "رقم الطلب",
    "OrderPendingInfo": "طلبك قيد المعالجة",
    "OrderProcessingDescription": "طلبك قيد التحضير",
    "OrderReceived": "تم استلام الطلب",
    "OrderReceivedTitle": "تم استلام طلبك",
    "OrderRecordAdded": "تم إنشاء سجل الطلب",
    "OrderRequest": "طلب الشراء",
    "OrderRequestInfo": "تم استلام طلب الشراء الخاص بك",
    "OrderSummary": "ملخص الطلب",
    "OrderTracking": "تتبع الطلب",
    "Orders": "الطلبات",
    "OutOfStock": "غير متوفر",
    "Overview": "نظرة عامة",
    "Packaging": "التغليف",
    "PackagingLabel": "التغليف",
    "Password": "كلمة المرور",
    "PasswordPlaceholder": "كلمة المرور",
    "PasswordRepeat": "تكرار كلمة المرور",
    "PaymentAndDelivery": "الدفع والتوصيل",
    "PaymentApprovalPending": "في انتظار موافقة الدفع",
    "PaymentErrorDescription": "حدث خطأ أثناء الدفع",
    "PaymentFailed": "فشل الدفع",
    "PaymentFailedTitle": "فشل الدفع",
    "PaymentInfo": "معلومات الدفع",
    "PaymentMethod": "طريقة الدفع",
    "PaymentMethods": "طرق الدفع",
    "PaymentStatus": "حالة الدفع",
    "PaymentSuccessful": "تم الدفع بنجاح",
    "Phone": "الهاتف",
    "PhonePlaceholder": "+970 5XX XXX XXX",
    "Pinterest": "بينتريست",
    "PleaseLogin": "يرجى تسجيل الدخول",
    "PleaseWait": "يرجى الانتظار",
    "PreOrder": "طلب مسبق",
    "PreOrderOpen": "مفتوح للطلب المسبق",
    "Preparing": "قيد التحضير",
    "PreparingDescription": "طلبك قيد التحضير",
    "PreviousSlide": "الشريحة السابقة",
    "PriceDropNotificationOn": "إشعار انخفاض السعر مفعل",
    "PriceHighToLow": "السعر من الأعلى إلى الأقل",
    "PriceLowToHigh": "السعر من الأقل إلى الأعلى",
    "PriceRange": "نطاق السعر",
    "PrivacyPolicy": "سياسة الخصوصية",
    "ProceedToCheckout": "المتابعة للدفع",
    "ProcessFailed": "فشلت المعالجة",
    "Processing": "قيد المعالجة",
    "Product": "المنتج",
    "ProductAddFailed": "فشل إضافة المنتج",
    "ProductAdded": "تمت إضافة المنتج",
    "ProductAddedToCart": "تمت إضافة المنتج إلى السلة",
    "ProductAddedToFavorites": "تمت إضافة المنتج إلى المفضلة",
    "ProductDescription": "وصف المنتج",
    "ProductImage": "صورة المنتج",
    "ProductLink": "رابط المنتج",
    "ProductNotAvailable": "المنتج غير متاح",
    "ProductNotFound": "المنتج غير موجود",
    "ProductPrepared": "تم تحضير المنتج",
    "ProductPreparedDesc": "يتم تحضير منتجك حسب الطلب",
    "ProductRemovedFromFavorites": "تمت إزالة المنتج من المفضلة",
    "Production": "الإنتاج",
    "ProductionInDaysJS": "أيام للإنتاج",
    "ProductionQualityAlt": "جودة الإنتاج",
    "ProductionStoryDesc": "كل منتج يُصنع بعناية",
    "ProtectivePackaging": "تغليف واقي",
    "PurchasedProducts": "المنتجات المشتراة",
    "QualityPrint": "طباعة عالية الجودة",
    "QualityPrintDesc": "ألوان زاهية وتفاصيل حادة",
    "Quantity": "الكمية",
    "RateProduct": "تقييم المنتج",
    "RateProductShort": "تقييم",
    "ReasonChangedMind": "غيرت رأيي",
    "ReasonDamagedProduct": "المنتج تالف",
    "ReasonNotAsExpected": "ليس كما توقعت",
    "ReasonWrongProduct": "تم استلام منتج خاطئ",
    "RecipientPlaceholder": "اسم المستلم",
    "Register": "تسجيل",
    "RegisteredEmail": "البريد الإلكتروني المسجل",
    "RegisteredEmailUsed": "هذا البريد الإلكتروني مسجل بالفعل",
    "RemoveFromFavorites": "إزالة من المفضلة",
    "RemoveProduct": "إزالة المنتج",
    "ResetPassword": "إعادة تعيين كلمة المرور",
    "ResetPasswordDescription": "تعيين كلمة المرور الجديدة",
    "ResultsFound": "نتائج تم العثور عليها",
    "ReturnDescriptionPlaceholder": "اشرح سبب الإرجاع",
    "ReturnExchange": "الإرجاع والاستبدال",
    "ReturnGuarantee": "ضمان الإرجاع",
    "ReturnHome": "العودة إلى الرئيسية",
    "ReturnProcess": "عملية الإرجاع",
    "ReturnProcessActive": "بدأت عملية الإرجاع",
    "ReturnReason": "سبب الإرجاع",
    "ReturnRequest": "طلب إرجاع",
    "ReturnToCartAndRetry": "العودة إلى السلة والمحاولة مرة أخرى",
    "ReturnToHome": "العودة إلى الرئيسية",
    "ReturnToLogin": "العودة إلى تسجيل الدخول",
    "Review": "تقييم",
    "Reviews": "التقييمات",
    "Rotate": "تدوير",
    "Sale": "تخفيض",
    "Save": "حفظ",
    "SaveAddress": "حفظ العنوان",
    "SaveAddressToAccount": "سيتم حفظ العنوان في حسابك",
    "SavedAddresses": "العناوين المحفوظة",
    "SavedNote": "تم حفظ الملاحظة",
    "Search": "بحث",
    "SearchProducts": "بحث عن منتجات",
    "SearchUnavailable": "الباحث غير متاح",
    "SecurePayment": "دفع آمن",
    "SecurePaymentDesc": "دفع آمن مع SSL 256 بت",
    "SecureShopping": "تسوق آمن",
    "SelectCity": "اختر المدينة",
    "SelectFrame": "اختر الإطار",
    "SelectFrameModel": "اختر نموذج الإطار",
    "SelectOption": "اختر الخيار",
    "SelectShippingCompany": "اختر شركة الشحن",
    "SelectSize": "اختر الحجم",
    "SendLink": "إرسال الرابط",
    "Sending": "جاري الإرسال",
    "Sent": "تم الإرسال",
    "SentViaEmail": "تم الإرسال عبر البريد الإلكتروني",
    "Share": "مشاركة",
    "ShareOnFacebook": "مشاركة على فيسبوك",
    "ShareOnWhatsApp": "مشاركة على واتساب",
    "Shipped": "تم الشحن",
    "ShippedDesc": "تم شحن منتجك",
    "ShippedDescription": "تم شحن طلبك",
    "Shipping": "الشحن",
    "ShippingFee": "رسوم الشحن",
    "ShippingLabel": "الشحن",
    "SimilarProducts": "منتجات مشابهة",
    "SizeOptions": "خيارات الحجم",
    "SlideN": "شريحة",
    "SpecialSelections": "اختيارات خاصة",
    "SslSecurePayment": "دفع آمن SSL",
    "StartShopping": "ابدأ التسوق",
    "Status": "الحالة",
    "StatusCancelled": "ملغي",
    "StatusDelivered": "تم التوصيل",
    "StatusOrderReceived": "تم استلام الطلب",
    "StatusPackaging": "قيد التغليف",
    "StatusPreparing": "قيد التحضير",
    "StatusReturnApproved": "تمت الموافقة على الإرجاع",
    "StatusReturnCompleted": "تم الإرجاع",
    "StatusReturnRequest": "طلب إرجاع",
    "StatusShipped": "تم الشحن",
    "StepApproved": "تمت الموافقة",
    "StepDelivered": "تم التوصيل",
    "StepInTransit": "في الطريق",
    "StepOrderReceived": "تم استلام الطلب",
    "StepPackaging": "قيد التغليف",
    "StepProcessClosed": "تم إغلاق العملية",
    "StepProductionPreparing": "تحضير الإنتاج",
    "StepRequestReceived": "تم استلام الطلب",
    "StepReturnCompleted": "تم الإرجاع",
    "Subcategories": "التصنيفات الفرعية",
    "SubmitRequest": "إرسال الطلب",
    "SubmitReview": "إرسال التقييم",
    "Subscribe": "اشتراك",
    "SubscribeToNewsletter": "اشترك في النشرة البريدية",
    "Subtotal": "المجموع الفرعي",
    "SuccessfullySubscribed": "تم الاشتراك بنجاح",
    "SupportContactInfo": "معلومات الاتصال بالدعم",
    "TechnicalSpecs": "المواصفات الفنية",
    "TermsAccepted": "أوافق على الشروط",
    "TermsOfUse": "شروط الاستخدام",
    "TikTok": "تيك توك",
    "Total": "المجموع",
    "TotalOrders": "إجمالي الطلبات",
    "TotalSpent": "إجمالي الإنفاق",
    "TrackOrder": "تتبع الطلب",
    "TrackingNumber": "رقم التتبع",
    "TransactionTime": "وقت المعاملة",
    "TryDifferentCategoryOrSearch": "جرب تصنيفاً مختلفاً أو بحثاً آخر",
    "TurkeyWideShipping": "توصيل إلى جميع مناطق فلسطين",
    "UnauthorizedAccess": "وصول غير مصرح به",
    "UndamagedDelivery": "توصيل بدون تلف",
    "UndamagedDeliveryDescription": "توصيل بدون تلف مع تغليف دقيق",
    "UnitPrice": "سعر الوحدة",
    "UpdatePassword": "تحديث كلمة المرور",
    "UserAgreement": "اتفاقية المستخدم",
    "VerificationSuccessDescription": "تم التحقق من حسابك بنجاح",
    "VerificationSuccessful": "تم التحقق بنجاح",
    "VerifyDeliveryInfo": "تحقق من معلومات التوصيل",
    "VibrantColors": "ألوان زاهية",
    "VideoTutorial": "فيديو تعليمي",
    "ViewAll": "عرض الكل",
    "ViewAll5Piece": "عرض جميع مجموعات 5 قطع",
    "ViewAllProducts": "عرض جميع المنتجات",
    "ViewAllResults": "عرض جميع النتائج",
    "ViewDeals": "عرض العروض",
    "WelcomeToAccount": "مرحباً بك في حسابك",
    "WhatsApp": "واتساب",
    "WhatsAppContact": "اتصال واتساب",
    "WhatsAppSupport": "دعم واتساب",
    "WriteFirstReview": "اكتب أول تقييم",
    "WriteReview": "كتابة تقييم",
    "X": "X",
    "YouTube": "يوتيوب",
    "YourComment": "تعليقك",
    "YourFullName": "اسمك الكامل",
    "YourOrderPreparedWithCare": "طلبك قيد التحضير بعناية",
    "ZoomIn": "تكبير",
    "ZoomOut": "تصغير",
}

def parse_existing_keys(resx_path):
    existing = set()
    if not os.path.exists(resx_path):
        return existing
    tree = ET.parse(resx_path)
    root = tree.getroot()
    for data in root.findall("data"):
        name = data.get("name")
        if name:
            existing.add(name)
    return existing

def add_entries_to_resx(resx_path, key_values, existing_keys):
    file_exists = os.path.exists(resx_path)
    if file_exists:
        tree = ET.parse(resx_path)
        root = tree.getroot()
    else:
        root = ET.Element("root")
        # Add resheader entries
        headers = [
            ("resmimetype", "text/microsoft-resx"),
            ("version", "2.0"),
            ("reader", "System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"),
            ("writer", "System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"),
        ]
        for name, value in headers:
            h = ET.SubElement(root, "resheader", name=name)
            v = ET.SubElement(h, "value")
            v.text = value
        tree = ET.ElementTree(root)

    added = 0
    skipped = 0
    for key in keys:
        if key in existing_keys:
            skipped += 1
            continue
        if key not in key_values:
            print(f"  WARNING: No translation for key '{key}'")
            continue
        data = ET.SubElement(root, "data", name=key)
        data.set("{http://www.w3.org/XML/1998/namespace}space", "preserve")
        val = ET.SubElement(data, "value")
        val.text = key_values[key]
        added += 1

    if added > 0:
        # Write with proper formatting
        ET.indent(tree, space="  ")
        tree.write(resx_path, encoding="utf-8", xml_declaration=True)
    
    return added, skipped

print("=== SharedResource.resx Güncelleme ===")
print(f"Toplam key sayısı: {len(keys)}")

for lang, values, label in [
    ("en", key_to_en, "İngilizce"),
    ("ar", ar_values, "Arapça"),
]:
    resx_path = f"FilistinProje.Web/Resources/SharedResource.{lang}.resx"
    existing = parse_existing_keys(resx_path)
    print(f"\n--- {label} ({lang}) ---")
    print(f"  Dosya: {resx_path}")
    print(f"  Mevcut key: {len(existing)}")
    
    added, skipped = add_entries_to_resx(resx_path, values, existing)
    print(f"  Eklenen: {added}")
    print(f"  Atlanan (zaten var): {skipped}")
    
    # Verify
    new_existing = parse_existing_keys(resx_path)
    print(f"  Yeni toplam: {len(new_existing)}")

print("\n=== TAMAM ===")
