Build started...
Build succeeded.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "AdSoyad" text NOT NULL,
        "Sehir" text NOT NULL,
        "SifreSifirlamaToken" text,
        "SifreSifirlamaGecerlilik" timestamp with time zone,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "BultenAbonelikleri" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" text NOT NULL,
        "KayitTarihi" timestamp with time zone NOT NULL,
        "AktifMi" boolean NOT NULL,
        "IpAdresi" text,
        CONSTRAINT "PK_BultenAbonelikleri" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "HomePageSections" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SectionType" integer NOT NULL,
        "Enabled" boolean NOT NULL,
        "SortOrder" integer NOT NULL,
        "Title" text NOT NULL,
        "Subtitle" text NOT NULL,
        "ViewAllText" text,
        "ViewAllUrl" text,
        "ImageUrl" text,
        "Description" text,
        "ButtonText" text,
        "ButtonUrl" text,
        CONSTRAINT "PK_HomePageSections" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "IletisimMesajlari" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AdSoyad" text NOT NULL,
        "Email" text NOT NULL,
        "Konu" text NOT NULL,
        "Mesaj" text NOT NULL,
        "Tarih" timestamp with time zone NOT NULL,
        "IpAdresi" text,
        "OkunduMu" boolean NOT NULL,
        CONSTRAINT "PK_IletisimMesajlari" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "KargoFirmalari" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Ad" text NOT NULL,
        "Kod" text NOT NULL,
        "LogoUrl" text,
        "Telefon" text,
        "TakipUrl" text,
        "GondericiUnvan" text NOT NULL,
        "GondericiAdres" text NOT NULL,
        "GondericiTelefon" text NOT NULL,
        "AktifMi" boolean NOT NULL,
        "VarsayilanMi" boolean NOT NULL,
        "Fiyat" numeric NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_KargoFirmalari" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "Kategoriler" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Ad" text NOT NULL,
        "KisaAciklama" text NOT NULL,
        "Aciklama" text NOT NULL,
        "Slug" text,
        "GorselUrl" text,
        "BannerUrl" text,
        "SeoTitle" text NOT NULL,
        "SeoDescription" text NOT NULL,
        "UstMetin" text NOT NULL,
        "AltMetin" text NOT NULL,
        "KampanyaEtiketi" text NOT NULL,
        "UrunSiralamaTipi" text NOT NULL,
        "Sira" integer NOT NULL,
        "AktifMi" boolean NOT NULL,
        "ParentKategoriId" integer,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_Kategoriler" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Kategoriler_Kategoriler_ParentKategoriId" FOREIGN KEY ("ParentKategoriId") REFERENCES "Kategoriler" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "Kuponlar" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Kod" character varying(20) NOT NULL,
        "Tip" integer NOT NULL,
        "Deger" numeric NOT NULL,
        "MinSepetTutari" numeric NOT NULL,
        "SonKullanmaTarihi" timestamp with time zone NOT NULL,
        "KullanimLimiti" integer NOT NULL,
        "KullanilanMiktar" integer NOT NULL,
        "AktifMi" boolean NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_Kuponlar" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "KurumsalSayfalar" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Baslik" text NOT NULL,
        "Icerik" text NOT NULL,
        "UrlSlug" text NOT NULL,
        "Sira" integer NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_KurumsalSayfalar" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "SenTasarla" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "KullaniciId" text,
        "DosyaYolu" character varying(200) NOT NULL,
        "Olcu" character varying(50) NOT NULL,
        "Fiyat" numeric(18,2) NOT NULL,
        "Efekt" character varying(20) NOT NULL,
        "CercveliMi" boolean NOT NULL,
        "ParcaSayisi" character varying(50) NOT NULL,
        "OlusturmaTarihi" timestamp with time zone NOT NULL,
        "SepeteEklendi" boolean NOT NULL,
        "SessionId" character varying(50) NOT NULL,
        CONSTRAINT "PK_SenTasarla" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "SiteAyarlari" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SiteAdi" text NOT NULL,
        "MarkaAdi" text NOT NULL,
        "SiteBasligi" text NOT NULL,
        "SiteAciklamasi" text NOT NULL,
        "SiteLogoUrl" text NOT NULL,
        "FaviconUrl" text NOT NULL,
        "BaseUrl" text NOT NULL,
        "TemaRengi" text NOT NULL,
        "UstBarMesaji" text NOT NULL,
        "KampanyaMesaji" text NOT NULL,
        "UstBarEtkin" boolean NOT NULL,
        "UstBarHizi" double precision NOT NULL,
        "FooterAciklamasi" text NOT NULL,
        "Telefon" text NOT NULL,
        "Email" text NOT NULL,
        "Adres" text NOT NULL,
        "WhatsappNumarasi" text NOT NULL,
        "CalismaSaatleri" text NOT NULL,
        "FacebookUrl" text NOT NULL,
        "InstagramUrl" text NOT NULL,
        "TwitterUrl" text NOT NULL,
        "YoutubeUrl" text NOT NULL,
        "TiktokUrl" text NOT NULL,
        "PinterestUrl" text NOT NULL,
        "ParaBirimi" text NOT NULL,
        "KargoBedeli" numeric NOT NULL,
        "UcretsizKargoLimiti" numeric NOT NULL,
        "StokUyariLimiti" integer NOT NULL,
        "StoktaYokSatisIzni" boolean NOT NULL,
        "PaytrAktifMi" boolean NOT NULL,
        "PaytrTestModu" boolean NOT NULL,
        "PaytrMerchantId" text NOT NULL,
        "PaytrMerchantKeyProtected" text NOT NULL,
        "PaytrMerchantSaltProtected" text NOT NULL,
        "PaytrCallbackUrl" text NOT NULL,
        "PaytrBasariliDonusUrl" text NOT NULL,
        "PaytrBasarisizDonusUrl" text NOT NULL,
        "KargoFirmasi" text NOT NULL,
        "KargoTakipUrl" text NOT NULL,
        "SiparisTeslimSuresiGun" integer NOT NULL,
        "IadeHakkiGun" integer NOT NULL,
        "MetaTitle" text NOT NULL,
        "MetaDescription" text NOT NULL,
        "MetaKeywords" text NOT NULL,
        "GoogleAnalyticsId" text NOT NULL,
        "FacebookPixelId" text NOT NULL,
        "VarsayilanSosyalPaylasimGorseliUrl" text NOT NULL,
        "CookieMetni" text NOT NULL,
        "YeniSiparisMailBildirimi" boolean NOT NULL,
        "StokUyarisiMailBildirimi" boolean NOT NULL,
        "IadeTalebiMailBildirimi" boolean NOT NULL,
        "BildirimAliciEmail" text NOT NULL,
        "BakimModuAktif" boolean NOT NULL,
        "BakimModuMesaji" text NOT NULL,
        CONSTRAINT "PK_SiteAyarlari" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "Slaytlar" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Baslik" text NOT NULL,
        "AltBaslik" text NOT NULL,
        "Aciklama" text NOT NULL,
        "ResimUrl" text,
        "VideoUrl" text,
        "Tur" text NOT NULL,
        "Sira" integer NOT NULL,
        "AktifMi" boolean NOT NULL,
        "OlusturmaTarihi" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Slaytlar" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "UrunOzellikTanimlari" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Ad" text NOT NULL,
        "Kod" text NOT NULL,
        "UrunTipi" text NOT NULL,
        "AlanTipi" text NOT NULL,
        "YardimMetni" text NOT NULL,
        "Secenekler" text NOT NULL,
        "FiltredeGoster" boolean NOT NULL,
        "DetaySayfasindaGoster" boolean NOT NULL,
        "TeknikTablodaGoster" boolean NOT NULL,
        "AktifMi" boolean NOT NULL,
        "Sira" integer NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_UrunOzellikTanimlari" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "ZiyaretciLoglari" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "IpAdresi" text NOT NULL,
        "Url" text NOT NULL,
        "CihazBilgisi" text NOT NULL,
        "ReferansUrl" text,
        "KullaniciAdi" text,
        "Metod" text NOT NULL,
        "Sehir" text,
        "Ulke" text,
        "Tarayici" text,
        "CihazModeli" text,
        "IsletimSistemi" text,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_ZiyaretciLoglari" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "Adresler" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Baslik" text NOT NULL,
        "AdSoyad" text NOT NULL,
        "Telefon" text NOT NULL,
        "Sehir" text NOT NULL,
        "Ilce" text NOT NULL,
        "AcikAdres" text NOT NULL,
        "AppUserId" text NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_Adresler" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Adresler_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "Sepetler" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppUserId" text,
        "SessionId" text,
        "SonGuncellemeTarihi" timestamp with time zone NOT NULL,
        "TerkEdildi" boolean NOT NULL,
        "TerkEdilmeTarihi" timestamp with time zone,
        "HatirlatmaGonderildi" boolean NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_Sepetler" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Sepetler_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "Siparisler" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppUserId" text,
        "SiparisNo" text NOT NULL,
        "KuponKodu" text,
        "IndirimTutari" numeric NOT NULL,
        "MusteriAdSoyad" text NOT NULL,
        "Telefon" text NOT NULL,
        "Eposta" text NOT NULL,
        "Sehir" text NOT NULL,
        "Ilce" text NOT NULL,
        "AcikAdres" text NOT NULL,
        "ToplamTutar" numeric NOT NULL,
        "Durum" integer NOT NULL,
        "KargoTakipNo" text,
        "KargoFirmasiId" integer,
        "KargoFirmasi" text,
        "KargoUcreti" numeric NOT NULL,
        "Aciklama" text,
        "EmailHashKodu" text,
        "FaturaDosyaYolu" text,
        "FaturaDosyaAdi" text,
        "FaturaYuklendiMi" boolean NOT NULL,
        "FaturaYuklenmeTarihi" timestamp with time zone,
        "FaturaMailGonderildiMi" boolean NOT NULL,
        "FaturaMailGonderimTarihi" timestamp with time zone,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_Siparisler" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Siparisler_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "Urunler" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Baslik" text NOT NULL,
        "KisaAd" text NOT NULL,
        "Slug" text,
        "UrlYolu" text NOT NULL,
        "SKU" text NOT NULL,
        "Barkod" text NOT NULL,
        "Marka" text NOT NULL,
        "UrunTipi" text NOT NULL,
        "Etiketler" text NOT NULL,
        "KisaAciklama" text NOT NULL,
        "Aciklama" text NOT NULL,
        "TeknikOzellikler" text NOT NULL,
        "MalzemeBilgisi" text NOT NULL,
        "BakimTalimati" text NOT NULL,
        "PaketlemeBilgisi" text NOT NULL,
        "AnaGorselUrl" text NOT NULL,
        "StokDurumu" text NOT NULL,
        "Fiyat" numeric NOT NULL,
        "IndirimliFiyat" numeric,
        "Maliyet" numeric NOT NULL,
        "KdvOrani" numeric NOT NULL,
        "UretimSuresiGun" integer NOT NULL,
        "KargoyaVerilisSuresiGun" integer NOT NULL,
        "TahminiTeslimSuresiGun" integer NOT NULL,
        "AktifMi" boolean NOT NULL,
        "OneCikanMi" boolean NOT NULL,
        "YeniUrunMu" boolean NOT NULL,
        "KampanyaliMi" boolean NOT NULL,
        "AnaSayfadaGoster" boolean NOT NULL,
        "Sira" integer NOT NULL,
        "GoruntulenmeSayisi" integer NOT NULL,
        "SatisSayisi" integer NOT NULL,
        "FavoriSayisi" integer NOT NULL,
        "MinSiparisAdedi" integer NOT NULL,
        "MaxSiparisAdedi" integer,
        "SeoTitle" text NOT NULL,
        "SeoDescription" text NOT NULL,
        "SeoKeywords" text NOT NULL,
        "KategoriId" integer NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_Urunler" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Urunler_Kategoriler_KategoriId" FOREIGN KEY ("KategoriId") REFERENCES "Kategoriler" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "IadeTalepleri" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SiparisId" integer NOT NULL,
        "MusteriId" text NOT NULL,
        "Neden" text NOT NULL,
        "Aciklama" text,
        "IBAN" text,
        "Durum" integer NOT NULL,
        "AdminNotu" text,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_IadeTalepleri" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_IadeTalepleri_Siparisler_SiparisId" FOREIGN KEY ("SiparisId") REFERENCES "Siparisler" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "Favoriler" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppUserId" text NOT NULL,
        "UrunId" integer NOT NULL,
        "FiyatDustugundaBildir" boolean NOT NULL,
        "EskiFiyat" numeric,
        "SonBildirimTarihi" timestamp with time zone,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_Favoriler" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Favoriler_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Favoriler_Urunler_UrunId" FOREIGN KEY ("UrunId") REFERENCES "Urunler" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "HomePageSectionProducts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SectionId" integer NOT NULL,
        "UrunId" integer NOT NULL,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_HomePageSectionProducts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HomePageSectionProducts_HomePageSections_SectionId" FOREIGN KEY ("SectionId") REFERENCES "HomePageSections" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_HomePageSectionProducts_Urunler_UrunId" FOREIGN KEY ("UrunId") REFERENCES "Urunler" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "UrunOzellikDegerleri" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UrunId" integer NOT NULL,
        "UrunOzellikTanimiId" integer NOT NULL,
        "Deger" text NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_UrunOzellikDegerleri" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UrunOzellikDegerleri_UrunOzellikTanimlari_UrunOzellikTanimi~" FOREIGN KEY ("UrunOzellikTanimiId") REFERENCES "UrunOzellikTanimlari" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UrunOzellikDegerleri_Urunler_UrunId" FOREIGN KEY ("UrunId") REFERENCES "Urunler" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "UrunResimleri" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ResimYolu" text NOT NULL,
        "Baslik" text NOT NULL,
        "AltMetin" text NOT NULL,
        "MedyaTipi" text NOT NULL,
        "MedyaAlani" text NOT NULL,
        "VideoUrl" text NOT NULL,
        "ThumbnailYolu" text NOT NULL,
        "MobilResimYolu" text NOT NULL,
        "Etiketler" text NOT NULL,
        "Sira" integer NOT NULL,
        "VarsayilanMi" boolean NOT NULL,
        "UrunSecenekId" integer,
        "UrunId" integer NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_UrunResimleri" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UrunResimleri_Urunler_UrunId" FOREIGN KEY ("UrunId") REFERENCES "Urunler" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "UrunSecenekleri" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UrunId" integer NOT NULL,
        "Olcu" text NOT NULL,
        "CerceveTipi" text NOT NULL,
        "CerceveRengi" text NOT NULL,
        "CerceveKalinligi" text NOT NULL,
        "MalzemeTuru" text NOT NULL,
        "Yon" text NOT NULL,
        "ParcaSayisi" integer NOT NULL,
        "VaryantSku" text NOT NULL,
        "KisilestirmeMetni" text NOT NULL,
        "OzelTasarimNotu" text NOT NULL,
        "FiyatFarki" numeric NOT NULL,
        "SatisFiyati" numeric NOT NULL,
        "MaliyetFiyati" numeric NOT NULL,
        "StokAdedi" integer NOT NULL,
        "UretimSuresiGun" integer NOT NULL,
        "Desi" numeric NOT NULL,
        "GorselUrl" text NOT NULL,
        "AktifMi" boolean NOT NULL,
        "VarsayilanMi" boolean NOT NULL,
        "TukeninceGizle" boolean NOT NULL,
        "OnSipariseAcikMi" boolean NOT NULL,
        "Sira" integer NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_UrunSecenekleri" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UrunSecenekleri_Urunler_UrunId" FOREIGN KEY ("UrunId") REFERENCES "Urunler" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "Yorumlar" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UrunId" integer NOT NULL,
        "AppUserId" text,
        "AdSoyad" character varying(50) NOT NULL,
        "YorumMetni" text NOT NULL,
        "Puan" integer NOT NULL,
        "OnayliMi" boolean NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_Yorumlar" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Yorumlar_Urunler_UrunId" FOREIGN KEY ("UrunId") REFERENCES "Urunler" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "SepetItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SepetId" integer NOT NULL,
        "UrunId" integer NOT NULL,
        "UrunSecenekId" integer,
        "Adet" integer NOT NULL,
        "Fiyat" numeric NOT NULL,
        "UrunBaslik" text NOT NULL,
        "UrunResimUrl" text NOT NULL,
        "CerceveModeli" text NOT NULL,
        "SecenekAdi" text,
        "MusteriNotu" character varying(500),
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_SepetItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SepetItems_Sepetler_SepetId" FOREIGN KEY ("SepetId") REFERENCES "Sepetler" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SepetItems_UrunSecenekleri_UrunSecenekId" FOREIGN KEY ("UrunSecenekId") REFERENCES "UrunSecenekleri" ("Id"),
        CONSTRAINT "FK_SepetItems_Urunler_UrunId" FOREIGN KEY ("UrunId") REFERENCES "Urunler" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE TABLE "SiparisDetaylari" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SiparisId" integer NOT NULL,
        "UrunSecenekId" integer,
        "Adet" integer NOT NULL,
        "BirimFiyat" numeric NOT NULL,
        "UrunId" integer NOT NULL,
        "CerceveModeli" text NOT NULL,
        "MusteriNotu" character varying(500),
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_SiparisDetaylari" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SiparisDetaylari_Siparisler_SiparisId" FOREIGN KEY ("SiparisId") REFERENCES "Siparisler" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SiparisDetaylari_UrunSecenekleri_UrunSecenekId" FOREIGN KEY ("UrunSecenekId") REFERENCES "UrunSecenekleri" ("Id"),
        CONSTRAINT "FK_SiparisDetaylari_Urunler_UrunId" FOREIGN KEY ("UrunId") REFERENCES "Urunler" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_Adresler_AppUserId" ON "Adresler" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_Favoriler_AppUserId" ON "Favoriler" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_Favoriler_UrunId" ON "Favoriler" ("UrunId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_HomePageSectionProducts_SectionId" ON "HomePageSectionProducts" ("SectionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_HomePageSectionProducts_UrunId" ON "HomePageSectionProducts" ("UrunId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_IadeTalepleri_SiparisId" ON "IadeTalepleri" ("SiparisId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_KargoFirmalari_Kod" ON "KargoFirmalari" ("Kod");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_Kategoriler_ParentKategoriId" ON "Kategoriler" ("ParentKategoriId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_Kategoriler_Slug" ON "Kategoriler" ("Slug") WHERE "Slug" IS NOT NULL AND "Slug" <> '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_SepetItems_SepetId" ON "SepetItems" ("SepetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_SepetItems_UrunId" ON "SepetItems" ("UrunId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_SepetItems_UrunSecenekId" ON "SepetItems" ("UrunSecenekId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_Sepetler_AppUserId" ON "Sepetler" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_SiparisDetaylari_SiparisId" ON "SiparisDetaylari" ("SiparisId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_SiparisDetaylari_UrunId" ON "SiparisDetaylari" ("UrunId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_SiparisDetaylari_UrunSecenekId" ON "SiparisDetaylari" ("UrunSecenekId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_Siparisler_AppUserId" ON "Siparisler" ("AppUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_Urunler_KategoriId" ON "Urunler" ("KategoriId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_Urunler_Slug" ON "Urunler" ("Slug") WHERE "Slug" IS NOT NULL AND "Slug" <> '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_UrunOzellikDegerleri_UrunId" ON "UrunOzellikDegerleri" ("UrunId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_UrunOzellikDegerleri_UrunOzellikTanimiId" ON "UrunOzellikDegerleri" ("UrunOzellikTanimiId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_UrunOzellikTanimlari_UrunTipi_Kod" ON "UrunOzellikTanimlari" ("UrunTipi", "Kod");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_UrunResimleri_UrunId_Sira" ON "UrunResimleri" ("UrunId", "Sira");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_UrunSecenekleri_UrunId" ON "UrunSecenekleri" ("UrunId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    CREATE INDEX "IX_Yorumlar_UrunId" ON "Yorumlar" ("UrunId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613194853_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260613194853_InitialCreate', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613195915_AddWholesalePrice') THEN
    ALTER TABLE "Urunler" ADD "TopFiyat" numeric;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613195915_AddWholesalePrice') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260613195915_AddWholesalePrice', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613202928_AddCustomerIdentityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "DogumTarihi" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613202928_AddCustomerIdentityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "KimlikFotografYolu" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613202928_AddCustomerIdentityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "KimlikNo" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613202928_AddCustomerIdentityFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260613202928_AddCustomerIdentityFields', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613203317_AddOrderDeliveryAndPrescriptionFields') THEN
    ALTER TABLE "Siparisler" ADD "ReceteDosyaYolu" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613203317_AddOrderDeliveryAndPrescriptionFields') THEN
    ALTER TABLE "Siparisler" ADD "TeslimatTipi" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613203317_AddOrderDeliveryAndPrescriptionFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260613203317_AddOrderDeliveryAndPrescriptionFields', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Urunler" ADD "AciklamaAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Urunler" ADD "AciklamaEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Urunler" ADD "BaslikAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Urunler" ADD "BaslikEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Urunler" ADD "KisaAciklamaAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Urunler" ADD "KisaAciklamaEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Urunler" ADD "SeoDescriptionAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Urunler" ADD "SeoDescriptionEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Urunler" ADD "SeoTitleAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Urunler" ADD "SeoTitleEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "AciklamaAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "AciklamaEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "AdAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "AdEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "AltMetinAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "AltMetinEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "KampanyaEtiketiAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "KampanyaEtiketiEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "KisaAciklamaAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "KisaAciklamaEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "SeoDescriptionAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "SeoDescriptionEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "SeoTitleAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "SeoTitleEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "UstMetinAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    ALTER TABLE "Kategoriler" ADD "UstMetinEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260613221038_AddMultiLanguageFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260613221038_AddMultiLanguageFields', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614073624_AddUserAddressField') THEN
    ALTER TABLE "AspNetUsers" ADD "Adres" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614073624_AddUserAddressField') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614073624_AddUserAddressField', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614075244_AddLoginRequiredSetting') THEN
    ALTER TABLE "SiteAyarlari" ADD "GirisZorunluMu" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614075244_AddLoginRequiredSetting') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614075244_AddLoginRequiredSetting', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614080356_AddWholesaleStatus') THEN
    ALTER TABLE "AspNetUsers" ADD "WholesaleStatus" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614080356_AddWholesaleStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614080356_AddWholesaleStatus', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614085324_AddSiteDegerlendirme') THEN
    CREATE TABLE "SiteDegerlendirmeleri" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AdSoyad" character varying(100) NOT NULL,
        "Eposta" character varying(200),
        "Puan" integer NOT NULL,
        "Baslik" character varying(200),
        "YorumMetni" character varying(2000) NOT NULL,
        "OnayliMi" boolean NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_SiteDegerlendirmeleri" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614085324_AddSiteDegerlendirme') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614085324_AddSiteDegerlendirme', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614092149_AddStockOutGrayDisplay') THEN
    ALTER TABLE "SiteAyarlari" ADD "StokBiteniGriGoster" boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614092149_AddStockOutGrayDisplay') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614092149_AddStockOutGrayDisplay', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614092652_AddGiftWrapFields') THEN
    ALTER TABLE "Urunler" ADD "HediyePaketFiyati" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614092652_AddGiftWrapFields') THEN
    ALTER TABLE "Urunler" ADD "HediyePaketiVarMi" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614092652_AddGiftWrapFields') THEN
    ALTER TABLE "SiparisDetaylari" ADD "HediyePaketFiyati" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614092652_AddGiftWrapFields') THEN
    ALTER TABLE "SiparisDetaylari" ADD "HediyePaketi" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614092652_AddGiftWrapFields') THEN
    ALTER TABLE "SepetItems" ADD "HediyePaketFiyati" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614092652_AddGiftWrapFields') THEN
    ALTER TABLE "SepetItems" ADD "HediyePaketi" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614092652_AddGiftWrapFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614092652_AddGiftWrapFields', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614101244_AddKargoBolgeSistemi') THEN
    CREATE TABLE "KargoBolgeler" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Ad" text NOT NULL,
        "Sira" integer NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_KargoBolgeler" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614101244_AddKargoBolgeSistemi') THEN
    CREATE TABLE "KargoBolgeFiyatlari" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "KargoFirmasiId" integer NOT NULL,
        "BolgeId" integer NOT NULL,
        "Fiyat" numeric NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_KargoBolgeFiyatlari" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_KargoBolgeFiyatlari_KargoBolgeler_BolgeId" FOREIGN KEY ("BolgeId") REFERENCES "KargoBolgeler" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_KargoBolgeFiyatlari_KargoFirmalari_KargoFirmasiId" FOREIGN KEY ("KargoFirmasiId") REFERENCES "KargoFirmalari" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614101244_AddKargoBolgeSistemi') THEN
    CREATE TABLE "KargoBolgeSehirler" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BolgeId" integer NOT NULL,
        "SehirAdi" text NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_KargoBolgeSehirler" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_KargoBolgeSehirler_KargoBolgeler_BolgeId" FOREIGN KEY ("BolgeId") REFERENCES "KargoBolgeler" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614101244_AddKargoBolgeSistemi') THEN
    CREATE INDEX "IX_KargoBolgeFiyatlari_BolgeId" ON "KargoBolgeFiyatlari" ("BolgeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614101244_AddKargoBolgeSistemi') THEN
    CREATE UNIQUE INDEX "IX_KargoBolgeFiyatlari_KargoFirmasiId_BolgeId" ON "KargoBolgeFiyatlari" ("KargoFirmasiId", "BolgeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614101244_AddKargoBolgeSistemi') THEN
    CREATE UNIQUE INDEX "IX_KargoBolgeSehirler_BolgeId_SehirAdi" ON "KargoBolgeSehirler" ("BolgeId", "SehirAdi");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614101244_AddKargoBolgeSistemi') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614101244_AddKargoBolgeSistemi', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614102323_AddSiparisKimlikFoto') THEN
    ALTER TABLE "Siparisler" ADD "KimlikFotoYolu" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614102323_AddSiparisKimlikFoto') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614102323_AddSiparisKimlikFoto', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614103327_AddBankaHesaplari') THEN
    CREATE TABLE "BankaHesaplari" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BankaAdi" text NOT NULL,
        "HesapSahibi" text NOT NULL,
        "IBAN" text NOT NULL,
        "SubeKodu" text,
        "HesapNo" text,
        "AktifMi" boolean NOT NULL,
        "Sira" integer NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_BankaHesaplari" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614103327_AddBankaHesaplari') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614103327_AddBankaHesaplari', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614222407_AddKapidaOdemeBedeli') THEN
    ALTER TABLE "SiteAyarlari" ADD "KapidaOdemeAktifMi" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614222407_AddKapidaOdemeBedeli') THEN
    ALTER TABLE "SiteAyarlari" ADD "KapidaOdemeHizmetBedeli" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614222407_AddKapidaOdemeBedeli') THEN
    ALTER TABLE "Siparisler" ADD "KapidaOdemeHizmetBedeli" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614222407_AddKapidaOdemeBedeli') THEN
    ALTER TABLE "Siparisler" ADD "OdemeYontemi" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614222407_AddKapidaOdemeBedeli') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614222407_AddKapidaOdemeBedeli', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614223525_AddKapidaOdemeLimit') THEN
    ALTER TABLE "SiteAyarlari" ADD "KapidaOdemeLimiti" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614223525_AddKapidaOdemeLimit') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614223525_AddKapidaOdemeLimit', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614225236_AddReceteGerekliKategori') THEN
    ALTER TABLE "Kategoriler" ADD "ReceteGerekliMi" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260614225236_AddReceteGerekliKategori') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260614225236_AddReceteGerekliKategori', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615140117_AddWhatsappSiparisFields') THEN
    ALTER TABLE "Urunler" ADD "FiyatGizliMi" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615140117_AddWhatsappSiparisFields') THEN
    ALTER TABLE "Urunler" ADD "WhatsappSiparisVarMi" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615140117_AddWhatsappSiparisFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260615140117_AddWhatsappSiparisFields', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615212141_AddToptanciMinSiparisTutari') THEN
    ALTER TABLE "SiteAyarlari" ADD "ToptanciMinSiparisTutari" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615212141_AddToptanciMinSiparisTutari') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260615212141_AddToptanciMinSiparisTutari', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615221301_AddToptanciUrunGrubu') THEN
    ALTER TABLE "Urunler" ADD "ToptanciUrunGrubuId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615221301_AddToptanciUrunGrubu') THEN
    CREATE TABLE "ToptanciUrunGruplari" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Ad" text NOT NULL,
        "Aciklama" text,
        "AktifMi" boolean NOT NULL,
        "Sira" integer NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_ToptanciUrunGruplari" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615221301_AddToptanciUrunGrubu') THEN
    CREATE TABLE "ToptanciIskontoOranlari" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ToptanciUrunGrubuId" integer NOT NULL,
        "MinAdet" integer NOT NULL,
        "IskontoYuzdesi" numeric NOT NULL,
        "AktifMi" boolean NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_ToptanciIskontoOranlari" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ToptanciIskontoOranlari_ToptanciUrunGruplari_ToptanciUrunGr~" FOREIGN KEY ("ToptanciUrunGrubuId") REFERENCES "ToptanciUrunGruplari" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615221301_AddToptanciUrunGrubu') THEN
    CREATE INDEX "IX_Urunler_ToptanciUrunGrubuId" ON "Urunler" ("ToptanciUrunGrubuId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615221301_AddToptanciUrunGrubu') THEN
    CREATE INDEX "IX_ToptanciIskontoOranlari_ToptanciUrunGrubuId" ON "ToptanciIskontoOranlari" ("ToptanciUrunGrubuId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615221301_AddToptanciUrunGrubu') THEN
    CREATE INDEX "IX_ToptanciUrunGruplari_AktifMi" ON "ToptanciUrunGruplari" ("AktifMi");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615221301_AddToptanciUrunGrubu') THEN
    ALTER TABLE "Urunler" ADD CONSTRAINT "FK_Urunler_ToptanciUrunGruplari_ToptanciUrunGrubuId" FOREIGN KEY ("ToptanciUrunGrubuId") REFERENCES "ToptanciUrunGruplari" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615221301_AddToptanciUrunGrubu') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260615221301_AddToptanciUrunGrubu', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260616122634_AddBasvuruTarihi') THEN
    ALTER TABLE "AspNetUsers" ADD "BasvuruTarihi" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260616122634_AddBasvuruTarihi') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260616122634_AddBasvuruTarihi', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260616124117_AddFilistinKargoBolgeleri') THEN
    ALTER TABLE "KargoBolgeler" ADD "Aciklama" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260616124117_AddFilistinKargoBolgeleri') THEN
    ALTER TABLE "KargoBolgeler" ADD "Ulke" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260616124117_AddFilistinKargoBolgeleri') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260616124117_AddFilistinKargoBolgeleri', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260619122952_AddSliderMultilingual') THEN
    ALTER TABLE "Slaytlar" ADD COLUMN IF NOT EXISTS "BaslikEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260619122952_AddSliderMultilingual') THEN
    ALTER TABLE "Slaytlar" ADD COLUMN IF NOT EXISTS "BaslikAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260619122952_AddSliderMultilingual') THEN
    ALTER TABLE "Slaytlar" ADD COLUMN IF NOT EXISTS "AltBaslikEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260619122952_AddSliderMultilingual') THEN
    ALTER TABLE "Slaytlar" ADD COLUMN IF NOT EXISTS "AltBaslikAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260619122952_AddSliderMultilingual') THEN
    ALTER TABLE "Slaytlar" ADD COLUMN IF NOT EXISTS "AciklamaEn" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260619122952_AddSliderMultilingual') THEN
    ALTER TABLE "Slaytlar" ADD COLUMN IF NOT EXISTS "AciklamaAr" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260619122952_AddSliderMultilingual') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260619122952_AddSliderMultilingual', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623204005_AddKampanyaBitisTarihi') THEN
    ALTER TABLE "Urunler" ADD "KampanyaBitisTarihi" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623204005_AddKampanyaBitisTarihi') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260623204005_AddKampanyaBitisTarihi', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623205857_AddCarkOdulleri') THEN
    CREATE TABLE "CarkOdulleri" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LabelTr" character varying(50) NOT NULL,
        "LabelEn" character varying(50) NOT NULL,
        "LabelAr" character varying(50) NOT NULL,
        "Tip" character varying(20) NOT NULL,
        "Deger" integer NOT NULL,
        "Renk" character varying(10) NOT NULL,
        "MesajTr" character varying(200),
        "MesajEn" character varying(200),
        "MesajAr" character varying(200),
        "Sira" integer NOT NULL,
        "AktifMi" boolean NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_CarkOdulleri" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623205857_AddCarkOdulleri') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260623205857_AddCarkOdulleri', '8.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624145319_AddHaberBandi') THEN
    CREATE TABLE "HaberBandi" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MetinTr" character varying(300) NOT NULL,
        "MetinEn" character varying(300) NOT NULL,
        "MetinAr" character varying(300) NOT NULL,
        "Link" character varying(500),
        "LinkMetniTr" character varying(100),
        "LinkMetniEn" character varying(100),
        "LinkMetniAr" character varying(100),
        "BgRenk" character varying(10) NOT NULL,
        "MetinRengi" character varying(10) NOT NULL,
        "Sira" integer NOT NULL,
        "AktifMi" boolean NOT NULL,
        "YeniSekme" boolean NOT NULL,
        "OlusturulmaTarihi" timestamp with time zone NOT NULL,
        "SilindiMi" boolean NOT NULL,
        CONSTRAINT "PK_HaberBandi" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624145319_AddHaberBandi') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260624145319_AddHaberBandi', '8.0.4');
    END IF;
END $EF$;
COMMIT;


