-- 1) VETERINER STETESKOP
INSERT INTO "Urunler" ("Baslik", "KisaAd", "Slug", "UrlYolu", "SKU", "Barkod", "Marka", "UrunTipi", "Etiketler", "KisaAciklama", "Aciklama", "TeknikOzellikler", "MalzemeBilgisi", "BakimTalimati", "PaketlemeBilgisi", "AnaGorselUrl", "StokDurumu", "Fiyat", "Maliyet", "KdvOrani", "UretimSuresiGun", "KargoyaVerilisSuresiGun", "TahminiTeslimSuresiGun", "AktifMi", "OneCikanMi", "YeniUrunMu", "KampanyaliMi", "AnaSayfadaGoster", "Sira", "GoruntulenmeSayisi", "SatisSayisi", "FavoriSayisi", "MinSiparisAdedi", "SeoTitle", "SeoDescription", "SeoKeywords", "KategoriId", "OlusturulmaTarihi", "HediyePaketFiyati", "HediyePaketiVarMi", "WhatsappSiparisVarMi", "FiyatGizliMi", "YayindaMi", "BaslikAr", "BaslikEn", "KisaAciklamaAr", "KisaAciklamaEn", "AciklamaAr", "AciklamaEn", "SeoTitleAr", "SeoTitleEn", "SeoDescriptionAr", "SeoDescriptionEn")
VALUES (
'Veteriner Steteskop �ift Tambur 60 cm',
'Steteskop 60 cm',
'veteriner-steteskop-cift-tambur-60cm',
'/Urun/Detay/veteriner-steteskop-cift-tambur-60cm',
'VET-CL-004',
'8692000000049',
'Panascope',
'Klinik Ekipman',
'steteskop,veteriner,muayene,oskultasyon',
'Veteriner kullanimi icin ozel tasarlanmis cift tambur ve cift borulu steteskop. 60 cm uzunluk, yedek set ile birlikte.',
'Veteriner hekimler icin ozel olarak dizayn edilmis profesyonel steteskop. Cift tambur ve cift boru yapisi sayesinde net oskultasyon saglar. Yedek set ile birlikte gelir. Muayene, klinik ve saha kullanimina uygundur.',
'Cift tambur, cift boru, 60 cm uzunluk, paslanmaz celik gogus parcasi',
'Paslanmaz celik ve medikal PVC',
'Serin ve kuru yerde saklayiniz. Temizlik icin alkollu bez kullaniniz.',
'Orijinal kutusu ve yedek set ile birlikte',
'/img/products/vet-stethoscope.jpg',
'Stokta', 220, 90, 20, 1, 1, 3, true, true, true, false, true, 9, 0, 0, 0, 1,
'Veteriner Steteskop Cift Tambur 60 cm - 7ANRPS48',
'Veteriner kullanimi icin cift tambur steteskop',
'steteskop,veteriner,muayene',
70, NOW(), 0, false, true, false, true,
'سماعة طبية بيطرية مزدوجة 60 سم',
'Veterinary Stethoscope Dual Chest Piece 60 cm',
'سماعة بيطرية مزدوجة مصممة خصيصًا للاستخدام البيطري',
'Veterinary stethoscope specially designed for veterinary use with dual chest piece',
'سماعة بيطرية احترافية بنظام القناتين والصدر المزدوج. مناسبة للاستخدام في العيادات والميدان. تأتي مع طقم احتياطي.',
'Professional veterinary stethoscope with dual chest piece and dual tube system. Suitable for clinical and field use. Comes with spare set.',
'سماعة طبية بيطرية مزدوجة 60 سم',
'Veterinary Stethoscope Dual Chest Piece 60 cm',
'سماعة بيطرية مزدوجة مصممة خصيصًا للاستخدام البيطري',
'Veterinary stethoscope specially designed for veterinary use'
);

-- 2) CERRAHI DIKIS SETI 7 PARCA
INSERT INTO "Urunler" ("Baslik", "KisaAd", "Slug", "UrlYolu", "SKU", "Barkod", "Marka", "UrunTipi", "Etiketler", "KisaAciklama", "Aciklama", "TeknikOzellikler", "MalzemeBilgisi", "BakimTalimati", "PaketlemeBilgisi", "AnaGorselUrl", "StokDurumu", "Fiyat", "Maliyet", "KdvOrani", "UretimSuresiGun", "KargoyaVerilisSuresiGun", "TahminiTeslimSuresiGun", "AktifMi", "OneCikanMi", "YeniUrunMu", "KampanyaliMi", "AnaSayfadaGoster", "Sira", "GoruntulenmeSayisi", "SatisSayisi", "FavoriSayisi", "MinSiparisAdedi", "SeoTitle", "SeoDescription", "SeoKeywords", "KategoriId", "OlusturulmaTarihi", "HediyePaketFiyati", "HediyePaketiVarMi", "WhatsappSiparisVarMi", "FiyatGizliMi", "YayindaMi", "BaslikAr", "BaslikEn", "KisaAciklamaAr", "KisaAciklamaEn", "AciklamaAr", "AciklamaEn", "SeoTitleAr", "SeoTitleEn", "SeoDescriptionAr", "SeoDescriptionEn")
VALUES (
'Cerrahi Dikis Seti 7 Parca Paslanmaz Celik',
'Dikis Seti 7 Parca',
'cerrahi-dikis-seti-7-parca',
'/Urun/Detay/cerrahi-dikis-seti-7-parca',
'VET-CL-005',
'8692000000056',
'VetCerrahi',
'Cerrahi Malzeme',
'dikis seti,cerrahi,veteriner,portegu, penset',
'Veteriner hekimler icin 7 parca paslanmaz celik cerrahi dikis seti. Ozel fermuARli tasima cantasi icerisinde.',
'Profesyonel veteriner hekimler icin tasarlanmis 7 parca cerrahi dikis seti. Tum aletler paslanmaz celikten imal edilmistir ve ozel fermuARli tasima cantasi icerisinde her alet icin ayri yuvasi bulunmaktadir. Icerigi: Makas portegu, bisturi sapi (10 numara bisturi ile kullanilir), penset disli, penset dissiz, makas, mosquite pens, hemostatik pens.',
'7 parca, paslanmaz celik, canta 18x14x3 cm, 250 gram',
'Paslanmaz celik cerrahi aletler',
'Kullanim sonrasi dezenfekte ediniz. Sterilizasyon icin otoklav kullaniniz.',
'FermuARli tasima cantasi icerisinde',
'/img/products/vet-suture-kit.jpg',
'Stokta', 350, 140, 20, 1, 1, 3, true, true, true, false, true, 10, 0, 0, 0, 1,
'Cerrahi Dikis Seti 7 Parca - 7ANRPS48',
'Veteriner hekimler icin 7 parca cerrahi dikis seti',
'cerrahi,dikis seti,veteriner,portegu',
70, NOW(), 0, false, true, false, true,
'طقم خياطة جراحي 7 قطع ستانلس ستيل',
'Surgical Suture Kit 7-Piece Stainless Steel',
'طقم خياطة جراحي مكون من 7 قطع من الفولاذ المقاوم للصدأ',
'Surgical suture kit of 7 pieces made of stainless steel',
'طقم خياطة جراحي احترافي مكون من 7 قطع من الفولاذ المقاوم للصدأ. جميع الأدوات مصممة خصيصًا للأطباء البيطريين.',
'Professional 7-piece surgical suture kit in stainless steel. All instruments designed specifically for veterinarians.',
'طقم خياطة جراحي 7 قطع ستانلس ستيل',
'Surgical Suture Kit 7-Piece Stainless Steel',
'طقم خياطة جراحي مكون من 7 قطع من الفولاذ المقاوم للصدأ',
'Surgical suture kit of 7 pieces made of stainless steel'
);

-- 3) BAKIR + VITAMIN B12 ENJEKSIYON 20 ML
INSERT INTO "Urunler" ("Baslik", "KisaAd", "Slug", "UrlYolu", "SKU", "Barkod", "Marka", "UrunTipi", "Etiketler", "KisaAciklama", "Aciklama", "TeknikOzellikler", "MalzemeBilgisi", "BakimTalimati", "PaketlemeBilgisi", "AnaGorselUrl", "StokDurumu", "Fiyat", "Maliyet", "KdvOrani", "UretimSuresiGun", "KargoyaVerilisSuresiGun", "TahminiTeslimSuresiGun", "AktifMi", "OneCikanMi", "YeniUrunMu", "KampanyaliMi", "AnaSayfadaGoster", "Sira", "GoruntulenmeSayisi", "SatisSayisi", "FavoriSayisi", "MinSiparisAdedi", "SeoTitle", "SeoDescription", "SeoKeywords", "KategoriId", "OlusturulmaTarihi", "HediyePaketFiyati", "HediyePaketiVarMi", "WhatsappSiparisVarMi", "FiyatGizliMi", "YayindaMi", "BaslikAr", "BaslikEn", "KisaAciklamaAr", "KisaAciklamaEn", "AciklamaAr", "AciklamaEn", "SeoTitleAr", "SeoTitleEn", "SeoDescriptionAr", "SeoDescriptionEn")
VALUES (
'Bakir + Vitamin B12 Enjeksiyon 20 ml - Buyukbas & Kucukbas',
'Bakir B12 Enjeksiyon',
'bakir-vitamin-b12-enjeksiyon-20ml',
'/Urun/Detay/bakir-vitamin-b12-enjeksiyon-20ml',
'VET-FRM-001',
'8692000000063',
'ShowVet',
'Ciftlik Ilac',
'bakir,b12,enjeksiyon,buyukbas,kucukbas,anemi',
'Buyukbas ve kucukbas hayvanlarda bakir eksikligi ve anemide kullanilan enjeksiyon. 20 ml, her mlde 20 mg bakir + 1 mg B12.',
'Buyukbas (sigir, dana) ve kucukbas (koyun, kuzu) hayvanlarda bakir eksikligi (hipokuroz) ve es zamanli anemi tedavisinde kullanilan enjektabl cozelti. Her ml 20 mg bakir (bakir metiyonat formunda) ve 1 mg Vitamin B12 icerir. Boyun bolgesine derin intramuskuler enjeksiyon yoluyla uygulanir. 50 kg vucut agirligi basina 20 mg bakir onerilir. Dozaj: Yetiskin sigir 4-6 ml, dana 2 ml, buzagi 1-2 ml, kuzu 0.5 ml. Geri cekme suresi: Et icin 21 gun.',
'20 ml, enjeksiyonluk cozelti, 20 mg/ml bakir + 1 mg/ml B12',
'Bakir metiyonat + Vitamin B12 enjeksiyon cozeltisi',
'25 C altinda serin ve kuru yerde, isiktan koruyarak saklayiniz. Acildiktan sonra 28 gun icinde tuketilmelidir.',
'Renkli cam sise, karton kutu icinde',
'/img/products/vet-copper-b12-injection.jpg',
'Stokta', 65, 25, 8, 1, 1, 3, true, true, true, false, true, 11, 0, 0, 0, 1,
'Bakir + Vitamin B12 Enjeksiyon 20 ml - 7ANRPS48',
'Buyukbas ve kucukbas hayvanlar icin bakir + B12 enjeksiyonu',
'bakir,b12,enjeksiyon,buyukbas,kucukbas',
73, NOW(), 0, false, true, false, true,
'حقنة نحاس + فيتامين ب12 20 مل',
'Copper + Vitamin B12 Injection 20 ml',
'حقنة لعلاج نقص النحاس وفقر الدم في الأبقار والأغنام',
'Injection for copper deficiency and anemia in cattle and sheep',
'محلول قابل للحقن لعلاج نقص النحاس (نحاس الدم) وفقر الدم المصاحب في الأبقار والأغنام. يحتوي كل مل على 20 ملغ نحاس و1 ملغ فيتامين ب12.',
'Injectable solution for the treatment of copper deficiency (hypocuprosis) and concurrent anemia in cattle and sheep. Each ml contains 20 mg copper and 1 mg Vitamin B12.',
'حقنة نحاس + فيتامين ب12 20 مل',
'Copper + Vitamin B12 Injection 20 ml',
'حقنة لعلاج نقص النحاس وفقر الدم في الأبقار والأغنام',
'Injection for copper deficiency and anemia in cattle and sheep'
);
